<a href="https://colab.research.google.com/github/sisifo3/P_T_1/blob/main/BinarySearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import math

In [ ]:
def binarySearch(A,n,T):
  i = 0
  L = 0
  R = n - 1
  while L <= R:
    i = i +1
    print(i)
    m = math.floor((L + R) / 2)
    print(m)
    if A[m] < T:
      L = m + 1
    elif A[m] > T:
      R = m - 1
    else:
      return m
  return unsuccessful

N = ['S8','S11','S9','S12','S10','S14','S13','S1','N4','S7','N1','S6','S4','S2','N2','N3','S5','S3']
A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
n = 18
T = 18

m = binarySearch(A,n,T)
print(m)



1
8
2
13
3
15
4
16
5
17
17


In [ ]:
#S8 = 

In [ ]:
#packa = ['S1','S14','S13','S12','S10','S11','S8','S9']
#packb = ['S4','N1','N2','S6','S7']
#packc = ['S3','N3','S5']


In [ ]:
#N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#N = ['S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#p = ['N1','S4','S2','N4']
#N = ['N4', 'S2','N3','S5','S4','N1','N2','S6','S7','S1','S14','S13','S12','S10','S11''S9','S8']
#p = ['N1','S4','S2','N4']



#for i in range(3): 
#  print(i)
#  print(N)    
  #N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#  n1,n2 = giveMetwo(N)
#  existInfect(n1,p)
#  existInfect(n2,p)
#  print(n1,n2)
#  N = n1


0
['N4', 'S2', 'N3', 'S5', 'S4', 'N1', 'N2', 'S6', 'S7', 'S1', 'S14', 'S13', 'S12', 'S10', 'S11S9', 'S8']
S6
S8
['N4', 'S2', 'N3', 'S5', 'S4', 'N1', 'N2', 'S6'] ['S7', 'S1', 'S14', 'S13', 'S12', 'S10', 'S11S9', 'S8']
1
['N4', 'S2', 'N3', 'S5', 'S4', 'N1', 'N2', 'S6']
S5
S6
['N4', 'S2', 'N3', 'S5'] ['S4', 'N1', 'N2', 'S6']
2
['N4', 'S2', 'N3', 'S5']
S2
exist
S5
['N4', 'S2'] ['N3', 'S5']


In [ ]:
#N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#N = ['S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#p = ['N1','S4','S2','N4']
#N = ['N4', 'S2','N3','S5','S4','N1','N2','S6','S7','S1','S14','S13','S12','S10','S11''S9','S8']
#p = ['N1','S4','S2','N4']
#


#for i in range(3): 
#  print(i)
#  print(N)    
  #N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#  n1,n2 = giveMetwo(N)
#  a = existInfect(n1,p)
  #b = existInfect(n2,p)


#  print(n1,n2)
#  N = n1

0
['N4', 'S2', 'S1', 'S14', 'S13', 'S12', 'S4', 'N1', 'S3', 'N3', 'S6', 'S10', 'S11', 'N2', 'S6', 'S7', 'S9', 'S8']
S3
S8
['N4', 'S2', 'S1', 'S14', 'S13', 'S12', 'S4', 'N1', 'S3'] ['N3', 'S6', 'S10', 'S11', 'N2', 'S6', 'S7', 'S9', 'S8']
1
['N4', 'S2', 'S1', 'S14', 'S13', 'S12', 'S4', 'N1', 'S3']
S14
S3
['N4', 'S2', 'S1', 'S14'] ['S13', 'S12', 'S4', 'N1', 'S3']
2
['N4', 'S2', 'S1', 'S14']
S2
exist
S14
['N4', 'S2'] ['S1', 'S14']


In [ ]:
#primero una funcion que parta en dos el array
#def giveMetwo(N):
  #print(N)
#  l = len(N)
  #print(l)
#  la = l/2
#  la = int(la)
  #print(la)
#  a = N[0:la] 
  #print(a)
#  b = N[la:l]
  #print(b)
#  return a,b


#i = 0
#N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']

#for i in range(4): 
#  print(i)    
  #N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#  n1,n2 = giveMetwo(N)
#  print(n1,n2)
#  N = n1

0
['N4', 'S2', 'S1', 'S14', 'S13', 'S12', 'S4', 'N1', 'S3'] ['N3', 'S6', 'S10', 'S11', 'N2', 'S6', 'S7', 'S9', 'S8']
1
['N4', 'S2', 'S1', 'S14'] ['S13', 'S12', 'S4', 'N1', 'S3']
2
['N4', 'S2'] ['S1', 'S14']
3
['N4'] ['S2']


In [ ]:
#Esta funcion tiene que revisar si el nodo esta infectado. 

#def existInfect(a,p):
#  a = 0
#  val = a[-1]
#  print(val)
#  if val in p:
#    print('exist')
#    a = 1
#  return a  



#N = ['N4', 'S2', 'S1',  'S14', 'S13','S12','S4','N1','S3','N3','S6','S10','S11','N2','S6','S7','S9','S8']
#a = ['N4', 'S2', 'S1', 'S14', 'S13', 'S12', 'S4', 'N1', 'S3']
#aa = ['N4', 'S2', 'S1', 'S14']
#aaa = ['N4', 'S2']
#p = ['N1','S4','S2','N4']

#existInfect(aaa,p)


S2
exist


In [ ]:
#buscamos una funcion que quite los nodos mayores que no son parte de la busqueda.

#def DisNode():
#  s1 = ['S1','S14','S13','S12','S10','S11','S9','S8']
#  s4 = ['N1','N2','S6','S7']
#  s3 = ['S3','N3','S5']

In [ ]:
#flujo del codigo.

      #primero partimos el array de nodos  a la mitad, tomamos ese nodo y lo buscamos
      #Cada vez que eliminemos un conjunto de nodos es necesario cambiar las probabilidades
        

In [ ]:
def binarySearch(A,n,T):
  i = 0
  L = 0
  R = n - 1
  while L <= R:
    i = i +1
    print(i)
    m = math.floor((L + R) / 2)
    print(m)
    if A[m] < T:
      L = m + 1
    elif A[m] > T:
      R = m - 1
    else:
      return m
  return unsuccessful

N = ['S8','S11','S9','S12','S10','S14','S13','S1','N4','S7','N1','S6','S4','S2','N2','N3','S5','S3']
A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
n = 40
T = 10

m = binarySearch(A,n,T)
print(m)

1
19
2
9
9


In [ ]:
MaCounts = np.zeros( (14, 2) )
print(MaCounts)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
def binarySearch(A,n,T):
  Mm = []
  i = 0
  L = 0
  R = n - 1
  while L <= R:
    i = i +1
    #print(i)
    m = math.floor((L + R) / 2)
    #print(m)
    Mm.append(m) 
    if A[m] < T:
      L = m + 1
    elif A[m] > T:
      R = m - 1
    else:
      return m , Mm
  return unsuccessful , Mm

N = ['S8','S11','S9','S12','S10','S14','S13','S1','N4','S7','N1','S6','S4','S2','N2','N3','S5','S3']
A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
n = 40
T = 10
MM = np.zeros((n,6))
#MM = []
lm = []

i = 0
j = 0

for T in A:
  m, Mm = binarySearch(A,n,T)
  #print(m)
  print(Mm)
  lm.append(Mm)
  j = 0
  for val in Mm:
    MM[i][j] = val
    #MM.append(val)
    j = j + 1
  i = i + 1 

print(MM)
print(lm)

[19, 9, 4, 1, 0]
[19, 9, 4, 1]
[19, 9, 4, 1, 2]
[19, 9, 4, 1, 2, 3]
[19, 9, 4]
[19, 9, 4, 6, 5]
[19, 9, 4, 6]
[19, 9, 4, 6, 7]
[19, 9, 4, 6, 7, 8]
[19, 9]
[19, 9, 14, 11, 10]
[19, 9, 14, 11]
[19, 9, 14, 11, 12]
[19, 9, 14, 11, 12, 13]
[19, 9, 14]
[19, 9, 14, 16, 15]
[19, 9, 14, 16]
[19, 9, 14, 16, 17]
[19, 9, 14, 16, 17, 18]
[19]
[19, 29, 24, 21, 20]
[19, 29, 24, 21]
[19, 29, 24, 21, 22]
[19, 29, 24, 21, 22, 23]
[19, 29, 24]
[19, 29, 24, 26, 25]
[19, 29, 24, 26]
[19, 29, 24, 26, 27]
[19, 29, 24, 26, 27, 28]
[19, 29]
[19, 29, 34, 31, 30]
[19, 29, 34, 31]
[19, 29, 34, 31, 32]
[19, 29, 34, 31, 32, 33]
[19, 29, 34]
[19, 29, 34, 37, 35]
[19, 29, 34, 37, 35, 36]
[19, 29, 34, 37]
[19, 29, 34, 37, 38]
[19, 29, 34, 37, 38, 39]
[[19.  9.  4.  1.  0.  0.]
 [19.  9.  4.  1.  0.  0.]
 [19.  9.  4.  1.  2.  0.]
 [19.  9.  4.  1.  2.  3.]
 [19.  9.  4.  0.  0.  0.]
 [19.  9.  4.  6.  5.  0.]
 [19.  9.  4.  6.  0.  0.]
 [19.  9.  4.  6.  7.  0.]
 [19.  9.  4.  6.  7.  8.]
 [19.  9.  0.  0.  0.  0.]
 [

In [ ]:
b = []
c = [4,5,2]

#a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
#a

[[1, 2, 3, 4], [5, 6], [7, 8, 9]]