<a href="https://colab.research.google.com/github/sisifo3/P_T_1/blob/main/BreadthFirstSearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
import numpy as np

In [220]:
uploaded = files.upload()

Saving NodeContact_2.csv to NodeContact_2.csv


In [240]:
df = pd.read_csv('NodeContact_2.csv')
df2 = pd.read_csv('Prob_f.csv')

In [234]:
df.head()

a   b   c   d
0  1  14   4   0
1  2   4   3   0
2  3  17   0   0
3  4  12  15  17
4  5  16   0   0

In [235]:
df2.head()

S     P
0  S1  0.97
1  S2  0.86
2  S3  0.13
3  S4  0.60
4  S5  0.89

In [ ]:
#Node N4 is equal to 18
#fn = 18 

In [241]:
dfA = df.to_numpy()

In [242]:
print(dfA)

[[ 1 14  4  0]
 [ 2  4  3  0]
 [ 3 17  0  0]
 [ 4 12 15 17]
 [ 5 16  0  0]
 [ 6  0  0  0]
 [ 7  6  0  0]
 [ 8  9  0  0]
 [ 9  7  0  0]
 [10  9  0  0]
 [11  8  0  0]
 [12 11 10  0]
 [13 12  0  0]
 [14 13 12  4]
 [15  7  6 16]
 [16  6  0  0]
 [17  5  0  0]
 [18  1  2  0]]


In [243]:
z = [18,1,2,0]

for n in z:
  if n != 0:
    x = dfA[n-1]
    print(x)
    mf = searchVector(x)
    print(mf)


[18  1  2  0]
[[1, 4, 12, 11, 8, 9, 7, 6], [2, 4, 12, 11, 8, 9, 7, 6]]
[ 1 14  4  0]
[[4, 12, 11, 8, 9, 7, 6], [14, 12, 11, 8, 9, 7, 6]]
[2 4 3 0]
[[4, 12, 11, 8, 9, 7, 6], [3, 17, 5, 16, 6]]


In [199]:
#para cualquier vector del  tipo
#x = [18,1,2,0]
#Te regresa el camino de nodos de tipo
#[1, 4, 12, 11, 8, 9, 7, 6]
#[2, 4, 12, 11, 8, 9, 7, 6] 

def searchVector(x):
  #x = [18,1,2,0]
  x2 = x
  w = 0
  m = []

  while (w != 30):
    w = w + 1
    n = searchNodo(x)  
    m.append(n)
    a = n[0]

    ww = 0
    for v in x:
      if v == a:
        x2[ww] = 0
      ww = ww + 1    
    
    x = x2
    if (x[1]==0 and x[2]==0  and x[3] == 0):
      break

  return m


x = [18,1,2,0]
mf = searchVector(x)
print(mf)

[[1, 4, 12, 11, 8, 9, 7, 6], [2, 4, 12, 11, 8, 9, 7, 6]]


In [146]:
#Para cualquier 
#x = [18,1,2,0]
#a = 1
#Entrega
#n = [1, 4, 12, 11, 8, 9, 7, 6]

#Para cualquier 
#x = [18,0,2,0]
#a = 2
#Entrega
#n = [2, 4, 12, 11, 8, 9, 7, 6]


def searchNodo(fo):
  ns =[]
  ii = 0

  
  while (ii != 50):
    nf = getOderM(fo)
    #print(nf)
    
    a = nf[3]
    a = a[0]
    a = int(a)
    #print('a')
    #print(a)
    
    ns.append(a)

    fo = dfA[a-1]
    #print(fo)

    if fo[1] == 0 & fo[2] == 0 & fo[3] == 0 :
      break
    ii = ii + 1
    
  return ns

x = [18,1,2,0]
n = searchNodo(x)
print('n')
print(n)

n
[1, 4, 12, 11, 8, 9, 7, 6]


In [106]:
#Para cada entrada tipo x
#x : [18, 1, 2, 0]
#Regresa una salida tipo: 
#[[0.   0.  ]
# [0.   0.  ]
# [2.   0.86]
# [1.   0.97]]


def getOderM(N):
  valPN = np.zeros([4,2])
  i = 0

  for val in N:
    if i != 0:
      valT = evalNode(val)
      valPN[i,0] = val
      valPN[i,1] = valT
    i = i + 1

  #print(valPN)
  #El valor mayor es el ultimo de la Matriz
  valS = valPN[valPN[:,1].argsort()] 
  #print(valS)
  return valS



x =  [18,1,2,0]
print(x)

da = getOderM(x)
print(da)

[18, 1, 2, 0]
[[0.   0.  ]
 [0.   0.  ]
 [2.   0.86]
 [1.   0.97]]


In [103]:
#esta funcion encuentra la probabilidad para un nodo dado 

def evalNode(a):
  p = df2['P']
  pn = p.to_numpy()
  p1 = 0

  if a != 0:
    p1 = pn[a - 1]

  return p1

a = 1
r = evalNode(a)
print(r)


0.97
