<a href="https://colab.research.google.com/github/sisifo3/P_T_1/blob/main/BreadthFirstSearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import math

In [ ]:
uploaded = files.upload()

Saving Prob_f.csv to Prob_f.csv


In [ ]:
df1 = pd.read_csv('NodeContact_2.csv')
df2 = pd.read_csv('Prob_f.csv')

In [ ]:
df1.head()

a   b   c   d
0  1   1   1   1
1  1  14   4   0
2  2   4   3   0
3  3  17   0   0
4  4  12  15  17

In [ ]:
df2.head()

S     P
0  S1  0.97
1  S2  0.86
2  S3  0.13
3  S4  0.60
4  S5  0.89

In [ ]:
#Node N4 is equal to 18
#fn = 18 

In [ ]:
dfA = df1.to_numpy()

In [ ]:
print(dfA)

[[ 1  1  1  1]
 [ 1 14  4  0]
 [ 2  4  3  0]
 [ 3 17  0  0]
 [ 4 12 15 17]
 [ 5 16  0  0]
 [ 6  0  0  0]
 [ 7  6  0  0]
 [ 8  9  0  0]
 [ 9  7  0  0]
 [10  9  0  0]
 [11  8  0  0]
 [12 11 10  0]
 [13 12  0  0]
 [14 13 12  4]
 [15  7  6 16]
 [16  6  0  0]
 [17  5  0  0]
 [18  1  2  0]]


In [ ]:
#Esta parte manda cada posible nodo y el algoritmo busca en todos 
#los posibles siguientes nodos

#[1, 14, 4, 0]
#[[4, 12, 11, 8, 9, 7, 6], [14, 12, 11, 8, 9, 7, 6]]

Nz = [[1,1,1,1],
 [ 1, 14,  4,  0],
 [ 2,  4,  3,  0],
 [ 3, 17,  0,  0],
 [ 4, 12, 15, 17],
 [ 5, 16,  0,  0],
 [ 6,  0,  0,  0],
 [ 7,  6,  0,  0],
 [ 8,  9,  0,  0],
 [ 9,  7,  0,  0],
 [10,  9,  0,  0],
 [11,  8,  0,  0],
 [12, 11, 10,  0],
 [13, 12,  0,  0],
 [14, 13, 12,  4],
 [15,  7,  6, 16],
 [16,  6,  0,  0],
 [17,  5,  0,  0],
 [18,  1,  2,  0]]

Nz1 = [[1,1,1,1],
      [18,  1,  2,  0],
      [ 1, 14,  4,  0],
      [ 2,  4,  3,  0], 
      [14, 13, 12,  4],
      [ 4, 12, 15, 17],
      [ 3, 17,  0,  0],
      [12, 11, 10,  0],
      [13, 12,  0,  0],
      [15,  7,  6, 16],
      [17,  5,  0,  0],
      [10,  9,  0,  0],
      [11,  8,  0,  0],
      [ 6,  0,  0,  0],
      [ 7,  6,  0,  0],
      [ 5, 16,  0,  0],
      [16,  6,  0,  0],
      [ 8,  9,  0,  0],
      [ 9,  7,  0,  0]]

pN = 17
zi = 0
found = 0
count = 0
cp = []

while (found != 1):
  if found == 1:
    break
  for z in Nz1:
    if found == 1:
      break  
    print(z)
    if (zi != 0):
      if found == 1:
        break
      #z = [18,1,2,0]
      N = []
      NextNodes = []
      for n in z:
        #print(n)
        if found == 1:
          break
        if n != 0:
          #print(n)
          x = Nz[n][:]
          #print(x)
          mf = searchVector(x)
          print(mf)
          #print(pN)
          found,count2 = foundPositive(mf,pN)
          #print(found)
          #print(count2)
          count = count + count2 
          cp.append(count)
          if found == 1:
            break
    zi = zi + 1

print(count)    
print(cp)

[1, 1, 1, 1]
[18, 1, 2, 0]
[[1, 4, 12, 11, 8, 9, 7, 6], [2, 4, 12, 11, 8, 9, 7, 6]]
[[4, 12, 11, 8, 9, 7, 6], [14, 12, 11, 8, 9, 7, 6]]
[[4, 12, 11, 8, 9, 7, 6], [3, 17, 5, 16, 6]]
39
[16, 30, 39]


In [ ]:
#Vamos a hacer un test a el algoritmo 
#poniendo un posible caso positivo
#se evalua con cuantos posibles nodos visita 
#Antes de encontrar el posible caso positivo.
#el mejor caso, el pero caso. 
#menor probabilidad - menor probabilidad.  

def foundPositive(N,pN):
  a = 0
  count = 0
  countEnd = 0 

  for m in N:
    for n in m:
      count = count + 1
      if (n == pN):
        a = 1
        countEnd = count
      
  if (a == 1):
    count = countEnd
  
  return a, count



#N = [[10, 12, 11, 8, 9, 7, 4], [14, 12, 11, 8, 9, 7, 6]]
N = [[1, 4, 12, 11, 8, 9, 7, 6], [2, 4, 12, 11, 8, 9, 7, 6]]
positiveNode = 1

a,c = foundPositive(N,positiveNode)
print(a)
print(c)

1
1


In [ ]:
#para cualquier vector del  tipo
#x = [18,1,2,0]
#Te regresa el camino de nodos de tipo
#[1, 4, 12, 11, 8, 9, 7, 6]
#[2, 4, 12, 11, 8, 9, 7, 6] 

def searchVector(x):
  #x = [18,1,2,0]
  x2 = x
  w = 0
  m = []

  while (w != 30):
    w = w + 1
    n = searchNodo(x)  
    m.append(n)
    a = n[0]

    ww = 0
    for v in x:
      if v == a:
        x2[ww] = 0
      ww = ww + 1    
    
    x = x2
    if (x[1]==0 and x[2]==0  and x[3] == 0):
      break

  return m


x = [18,1,2,0]
mf = searchVector(x)
print(mf)

[[1, 4, 12, 11, 8, 9, 7, 6], [2, 4, 12, 11, 8, 9, 7, 6]]


In [ ]:
#Para cualquier 
#x = [18,1,2,0]
#a = 1
#Entrega
#n = [1, 4, 12, 11, 8, 9, 7, 6]

#Para cualquier 
#x = [18,0,2,0]
#a = 2
#Entrega
#n = [2, 4, 12, 11, 8, 9, 7, 6]


def searchNodo(fo):
  ns =[]
  ii = 0

  
  while (ii != 50):
    nf = getOderM(fo)
    #print(nf)
    
    a = nf[3]
    a = a[0]
    a = int(a)
    #print('a')
    #print(a)
    
    ns.append(a)
    fo = dfA[a]
    #print(fo)

    if fo[1] == 0 & fo[2] == 0 & fo[3] == 0 :
      break
    ii = ii + 1
    
  return ns

x = [18,1,2,0]
n = searchNodo(x)
print('n')
print(n)

n
[1, 4, 12, 11, 8, 9, 7, 6]


In [ ]:
#Para cada entrada tipo x
#x : [18, 1, 2, 0]
#Regresa una salida tipo: 
#[[0.   0.  ]
# [0.   0.  ]
# [2.   0.86]
# [1.   0.97]]


def getOderM(N):
  valPN = np.zeros([4,2])
  i = 0

  for val in N:
    if i != 0:
      valT = evalNode(val)
      valPN[i,0] = val
      valPN[i,1] = valT
    i = i + 1

  #print(valPN)
  #El valor mayor es el ultimo de la Matriz
  valS = valPN[valPN[:,1].argsort()] 
  #print(valS)
  return valS



x =  [18,1,2,0]
print(x)

da = getOderM(x)
print(da)

[18, 1, 2, 0]
[[0.   0.  ]
 [0.   0.  ]
 [2.   0.86]
 [1.   0.97]]


In [ ]:
#esta funcion encuentra la probabilidad para un nodo dado 

def evalNode(a):
  p = df2['P']
  pn = p.to_numpy()
  p1 = 0

  if a != 0:
    p1 = pn[a - 1]

  return p1

a = 1
r = evalNode(a)
print(r)


0.97
